"""change

Revision ID: 6e8a359f0220
Revises: a2921614592e
Create Date: 2025-02-09 10:29:33.330348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8a359f0220'
down_revision = 'a2921614592e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_admin_')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin_', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
