"""change

Revision ID: a2921614592e
Revises: 2a3f004d5039
Create Date: 2025-02-09 10:28:10.899589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2921614592e'
down_revision = '2a3f004d5039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin_', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_admin_')

    # ### end Alembic commands ###
